class AdmProductPage:
    add_button_xpath = "//a[@data-original-title='Add New']"
    product_name_id = "input-name1"
    product_meta_id = "input-meta-title1"
    data_link_text = "Data"
    data_input_model = "input-model"
    save_button_xpath = "//button[@data-original-title='Save']"
    filter_input_id = "input-name"
    filter_button_id = "button-filter"
    body_of_selected_tag = "tbody"
    result_cells_tag = "td"